language: php

sudo: true

addons:
  apt:
    packages:
      - tidy


# Technique taken from https://github.com/GSA/asis/blob/e59f23ccc49fdc54fcbe5b12eb7b1dea196c5f34/.travis.yml
before_install:
  - travis_retry curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb && sudo dpkg -i elasticsearch-1.7.2.deb && true
  - 'echo ''script.disable_dynamic: false'' | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - 'echo ''index.number_of_shards: 1'' | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch start
  - pip install --user codecov

env:
  global:
    - DB=MYSQL CORE_RELEASE=3.1
    - MODULE_PATH=elastica

matrix:
  #allow_failures:
  #  - php: hhvm-nightly
  include:
    - php: 5.5
      env: DB=SQLITE
    - php: 5.5
      env: DB=MYSQL

before_script:
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit -c $MODULE_PATH/phpunit.xml $MODULE_PATH/tests
