Name: elasticaroutes
Before: '*'
After:
  - '#rootroutes'
  - '#coreroutes'
  - '#modelascontrollerroutes'
  - '#adminroutes'

Director:
  rules:
    'autocomplete' : 'ElasticaAutoCompleteController'
